.\" Manpage for squarepig.
.\" Contact tablet-mode@monochromatic.cc to correct errors or typos.
.TH SQUAREPIG 1 "04 August 2014" "Squarepig 0.2.0" "Squarepig"
.SH NAME
\fBsquarepig\fR - a playlist mangler
.SH SYNOPSIS
\fBsquarepig\fR [options]
.SH DESCRIPTION
\fBsquarepig\fR is a playlist mangler.
.SH OPTIONS
.TP
.B "--help (-h)"
Show a super-helpful help text.
.TP
.B "--playlist (-p)"
Path to playlist file that shall be loaded.
.TP
.B "--destination (-d)"
Path to target folder.
.TP
.B "--musicdir (-m)"
Prefix for file paths in playlist.
.TP
.B "--version (-V)"
Show currently installed version.
.SH BUGS
For the time being please refer to Squarepig's github site
(https://github.com/tablet-mode/squarepig) for a list of known bugs and to
report newly found ones.
.SH AUTHOR
Tablet Mode <tablet-mode@monochromatic.cc>
